### ISSUE TITLE
Multiplying a measure by itself without specifying the measurement attribute results in TypeError

### ISSUE THREAD

**Issue by OmenApps** [coddingtonbear/python-measurement#40]
```python
>>> from measurement.measures import Mass
>>> m = Mass(lb=135)
>>> print(m)
135 lb
>>> print(m*m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/measurement/base.py", line 346, in __mul__
    return type(self)(value=value, unit=self.unit.org_name)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/measurement/base.py", line 254, in __init__
    value = decimal.Decimal(value)
TypeError: conversion from Mass to Decimal is not supported
```

It seems like this should work and return 135 lb * 135 lb = 18,225 lb

**Comment by codingjoe** [comment]
@OmenApps good catch. However, I do believe this should raise an error. Since you can't multiply two masses (at least I don't know a unit for that). So what you can do is multiply a mass by a number. That should work and returns a multiple of that mass.
That being said, the error message is really misleading and an error should be raised differently.
Thanks for all the help, I will create a patch for this.
