### ISSUE TITLE
Update documentation to remind users that in Celsius/Farenheit scales, the zero point is not actually zero

### ISSUE THREAD

**Issue by Gagaro** [coddingtonbear/python-measurement#5]
Hello,

When doing operation on temperatures which are not in kelvin, the results are wrong. For example, for temperatures in celsius, the temperatures are first converted in kelvin before being added:

```Python
a = Temperature(c=10)  # k=283.15
b = Temperature(c=20)  # k=293.15
c = a + b  # Temperature(k=576.30)
```

And ``576.30 k = 303.15 c``. Thus ``a + b`` gives us ``Temperature(c=303.15)``.

**Comment by coddingtonbear** [comment]
Hrm -- I'm not sure how I never noticed that before, but I do have an idea of why it's broken.  Thanks for the heads-up, @gagaro!

**Comment by coddingtonbear** [comment]
Oh, actually, on reconsideration; I think that's probably the ~right implementation; there isn't really a situation in which one might have "negative heat energy", so I think relying upon addition using kelvin (absolute temperature) is probably the best option.

**Comment by Gagaro** [comment]
I had the issue because I needed to do the average of several temperatures. I had to do the operation on their value and recreate the object afterward:

```Python
a = Temperature(c=10)
b = Temperature(c=20)
c = Temperature(c=a.c + b.c)
```

I agree with you that that's a tricky issue, but you still don't have the value you're expecting. Maybe a warning in the documentation would be enough ?

Or testing the units for Temperature when doing an operation and doing it on the values rather than the standards if the units are the same ?

**Comment by coddingtonbear** [comment]
While speaking with a colleague about this (thanks @aarcro!) -- because I can totally see why somebody might expect the behavior you're describing -- we've came up with what we think is a reasonable suggestion:

Since when using temperature measurements (outside Kelvin) the zero point is completely arbitrary, the meaning of adding two Celsius values together for any sort of operation is mathematically unsound.  If you did want to just add a few degrees to a celsius number, you should probably consider using Kelvin as your second operand (since units Kelvin and degrees Celsius represent the same unit, just differing starts of the scale):

```
a = Temperature(c=10) + Temperature(k=20)
# a == Temperature(c=30)
```

That being said, right after I typed that out, you mentioned that you were taking an average -- I'm not sure that the current behavior is a problem for taking an average, do you not get a result of 25 degrees Celsius if you were to do something like:

```
c = (Temperature(c=20) + Temperature(c=30)/2
# c *should* be Temperature(c=25)
```

If you don't, that's a different kind of bug that I should take a moment to dig into.

**Comment by Gagaro** [comment]
Yes you're right, doing an average does work. My issue was that I was doing the average of multiple temperates using sum:

```Python
temperatures = [Temperature(c=20), Temperature(c=30)]
total = sum(temperatures, Temperature(c=0))
total /= len(temperatures)
```

Thus doing the addition of 3 temperatures instead of just 2.

**Comment by coddingtonbear** [comment]
Ahh!  I see how that would be confusing -- since using `Temperature(c=0)` as the start *seems* like it's almost the same thing as zero, but it isn't.  OK, I'll add something to the docs, but for future notice -- `Temperature(c=0)` isn't really a very good zero value -- but `Temperature(k=0)` is.

```python
temperatures = [Temperature(c=20), Temperature(c=30)]
total = sum(temperatures, Temperature(k=0))
value = (total /= len(temperatures))
value.c  # should print `25.0`
```

**Comment by Gagaro** [comment]
Yes I understood this after I post my comment :smile: . Documenting it should be enough indeed, thanks for the help !

**Comment by coddingtonbear** [comment]
Updated; thanks for the heads-up, @Gagaro !
